export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SIGN_OUT = 'SIGN_OUT';

export const TOGGLE_SETTINGS_VISIBLE = 'TOGGLE_SETTINGS_VISIBLE';
export const TOGGLE_CONTEXT_MENU_VISIBLE = 'TOGGLE_CONTEXT_MENU_VISIBLE';
export const CLOSE_CONTEXT_MENU = 'CLOSE_CONTEXT_MENU';
export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';

export const TOGGLE_MENU_VISIBLE = 'TOGGLE_MENU_VISIBLE';

export const GET_CLICK_ITEM = 'GET_CLICK_ITEM';

export const ADD_SOURCE_SUCCESS = 'ADD_SOURCE_SUCCESS';
export const ADD_SOURCE_FAIL = 'ADD_SOURCE_FAIL';

export const EDIT_SOURCE_FAIL = 'EDIT_SOURCE_FAIL';

export const TOGGLE_EDIT_SOURCE_VISIBLE = 'TOGGLE_EDIT_SOURCE_VISIBLE';
export const OPEN_EDIT_SOURCE = 'OPEN_EDIT_SOURCE';
export const CLOSE_EDIT_SOURCE = 'CLOSE_EDIT_SOURCE';

export const SHOW_CONFIRM_DIALOG = 'SHOW_CONFIRM_DIALOG';
export const HIDE_CONFIRM_DIALOG = 'HIDE_CONFIRM_DIALOG';

export const SOURCE_DUPLICATE_NOT_ADDED = 'SOURCE_DUPLICATE_NOT_ADDED';

export const GETSOURCES_SUCCESS = 'GETSOURCES_SUCCESS';
export const GETSOURCES_FAIL = 'GETSOURCES_FAIL';

export const GET_SOURCES_DATA_SUCCESS = 'GET_SOURCES_DATA_SUCCESS';
export const GET_SOURCES_DATA_FAIL = 'GET_SOURCES_DATA_FAIL';

export const GET_VIEW_MODE_SUCCESS = 'GET_VIEW_MODE_SUCCESS';
export const SET_VIEW_MODE_SUCCESS = 'SET_VIEW_MODE_SUCCESS';

export const GET_THEME_SUCCESS = 'GET_THEME_SUCCESS';
export const SET_THEME_SUCCESS = 'SET_THEME_SUCCESS';

export const SET_RELOAD = 'SET_RELOAD';

export const SELECT_RSS_SOURCE = 'SELECT_RSS_SOURCE';

export const ADD_FEED_TO_READ_LATER = 'ADD_FEED_TO_READ_LATER';
export const REMOVE_FEED_FROM_READ_LATER = 'REMOVE_FEED_FROM_READ_LATER';
export const REMOVE_FEED_DATA_FROM_READ_LATER = 'REMOVE_FEED_DATA_FROM_READ_LATER';
export const REMOVE_ALL_READ_LATER_FEEDS = 'REMOVE_ALL_READ_LATER_FEEDS';

export const GET_FEEDS_READLATER = 'GET_FEEDS_READLATER';
export const GET_FEEDS_READLATER_DATA = 'GET_FEEDS_READLATER_DATA';

export const GET_FEED_TEXT_SUCCESS = 'GET_FEED_TEXT_SUCCESS';
export const GET_FEED_TEXT_FAIL = 'GET_FEED_TEXT_FAIL';

export const CHECK_IS_READ_LATER_TEXT = 'CHECK_IS_READ_LATER_TEXT';
